=== manifoldfinance/defi-threat/src/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "description": "",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "minLength": 1
        },
        "title": {
            "type": "string",
            "minLength": 1
        },
        "description": {
            "type": "string",
            "minLength": 1
        },
        "references": {
            "type": "array",
            "items": {
                "required": [
                    "contract_address"
                ],
                "properties": {}
            }
        },
        "credits": {
            "type": "string",
            "minLength": 1
        },
        "vulnerability_type": {
            "type": "object",
            "properties": {
                "cwe": {
                    "type": "string",
                    "minLength": 1
                },
                "swc": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "cwe",
                "swc"
            ]
        },
        "severity": {
            "type": "number"
        },
        "affected": {
            "type": "object",
            "properties": {
                "contractName": {
                    "type": "string",
                    "minLength": 1
                },
                "address": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "contractName",
                "address"
            ]
        },
        "signature": {
            "type": "string",
            "minLength": 1
        }
    },
    "required": [
        "id",
        "title",
        "description",
        "references",
        "credits",
        "vulnerability_type",
        "severity",
        "affected",
        "signature"
    ]
}

=== manifoldfinance/defi-threat/catalog/13227.json
{
    "id": "CVE-2018-13227",
    "title": "Integer Overflow or Wraparound",
    "description": "The sell function of a smart contract implementation for MoneyChainNet (MCN), an Ethereum token, has an integer overflow in which \"amount * sellPrice\" can be zero, consequently reducing a seller's assets.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/ETHEREUMBLACK/sell%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/MoneyChainNetToken"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "MoneyChainNetToken",
        "address": "0x77727EF417696F95A10652cF2d02d6421DDA5048"
    },
    "signature": "649feaad833f4ca3539d83beedcabc3f"
}

=== manifoldfinance/defi-threat/catalog/13613.json
{
    "id": "CVE-2018-13613",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for CON0217, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/CON0217"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "CON0217",
        "address": "0xadaa8c29ab35c5bf74af37aa799904c7b283f11d"
    },
    "signature": "824466b0825253d415f371dfca752775"
}

=== manifoldfinance/defi-threat/catalog/13752.json
{
    "id": "CVE-2018-13752",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for Thread, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/Thread"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "Thread",
        "address": "0x9c3ed43fdd2664d6d0e5399cff4720106a544d0f"
    },
    "signature": "c5d1692d61e04ef626bbae2253006abb"
}

=== manifoldfinance/defi-threat/catalog/13530.json
{
    "id": "CVE-2018-13530",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for HunterCoin, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/HunterCoin"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "HunterCoin",
        "address": "0x248044753872e64c288b35b0e71e8b29222e3ab8"
    },
    "signature": "8f670379222a9a0b99f8b159f9d94a8d"
}

=== manifoldfinance/defi-threat/catalog/13158.json
{
    "id": "CVE-2018-13158",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for AssetToken, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/AssetToken"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "AssetToken",
        "address": "0x6248211b830ce0191c7643b19f5ddb059e018672"
    },
    "signature": "c7e0a4b49896a227d810ca4fdd1b894b"
}

=== manifoldfinance/defi-threat/catalog/13740.json
{
    "id": "CVE-2018-13740",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for OneChain, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/OneChain"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "OneChain",
        "address": "0x6b17bfa6930e7490ebd2874cef490074708f36b9"
    },
    "signature": "f818be4ab61fcfcd1e723225c5fae3f0"
}

=== manifoldfinance/defi-threat/catalog/11561.json
{
    "id": "CVE-2018-11561",
    "title": "Integer Overflow or Wraparound",
    "description": "An integer overflow in the unprotected distributeToken function of a smart contract implementation for EETHER (EETHER), an Ethereum ERC20 token, will lead to an unauthorized increase of an attacker's digital assets.\n",
    "references": [
        "https://github.com/rootclay/Audit-of-smart-contracts/blob/master/0x00a0cbe98e4d110b0fa82646152d77babf2951d0/README.md"
    ],
    "credits": "rootclay",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "ERC20Token",
        "address": "0x00a0cbe98e4d110b0fa82646152d77babf2951d0"
    },
    "signature": "f62a4eab795ea6edc83a98d4777a4f38"
}

=== manifoldfinance/defi-threat/catalog/13199.json
{
    "id": "CVE-2018-13199",
    "title": "Integer Overflow or Wraparound",
    "description": "The sell function of a smart contract implementation for ETHEREUMBLACK (ETCBK), an Ethereum token, has an integer overflow in which \"amount * sellPrice\" can be zero, consequently reducing a seller's assets.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/ETHEREUMBLACK/sell%20integer%20overflow.md"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "ETHEREUMBLACK",
        "address": "0xE2fA3d7B292c216390AbAd4c625d5f2524B85A1f"
    },
    "signature": "649feaad833f4ca3539d83beedcabc3f"
}
