=== manifoldfinance/defi-threat/src/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "description": "",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "minLength": 1
        },
        "title": {
            "type": "string",
            "minLength": 1
        },
        "description": {
            "type": "string",
            "minLength": 1
        },
        "references": {
            "type": "array",
            "items": {
                "required": [
                    "contract_address"
                ],
                "properties": {}
            }
        },
        "credits": {
            "type": "string",
            "minLength": 1
        },
        "vulnerability_type": {
            "type": "object",
            "properties": {
                "cwe": {
                    "type": "string",
                    "minLength": 1
                },
                "swc": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "cwe",
                "swc"
            ]
        },
        "severity": {
            "type": "number"
        },
        "affected": {
            "type": "object",
            "properties": {
                "contractName": {
                    "type": "string",
                    "minLength": 1
                },
                "address": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "contractName",
                "address"
            ]
        },
        "signature": {
            "type": "string",
            "minLength": 1
        }
    },
    "required": [
        "id",
        "title",
        "description",
        "references",
        "credits",
        "vulnerability_type",
        "severity",
        "affected",
        "signature"
    ]
}

=== manifoldfinance/defi-threat/catalog/14088.json
{
    "id": "CVE-2018-14088",
    "title": "Integer Overflow or Wraparound",
    "description": "An issue was discovered in a smart contract implementation for STeX White List (STE(WL)), an Ethereum token. The contract has an integer overflow. If the owner sets the value of amount to a large number then the \"amount * 1000000000000000\" will cause an integer overflow in withdrawToFounders().\n",
    "references": ["https://github.com/hellowuzekai/blockchains/blob/master/overflow3.md"],
    "credits": "hellowuzekai",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 9.8,
    "affected": {
        "contractName": "STeX_WL",
        "address": "0x1f31D1168efE4bD22D00D31FC425e5BcB54c75E7"
    },
    "signature": "d0ed0f00911a2bc181e6ea454b7457df"
}

=== manifoldfinance/defi-threat/catalog/13727.json
{
    "id": "CVE-2018-13727",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for Eastcoin, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/Eastcoin"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "Eastcoin",
        "address": "0x62c4d0fee81d9ec10581ffaca7ad976d76593fc3"
    },
    "signature": "c5d1692d61e04ef626bbae2253006abb"
}

=== manifoldfinance/defi-threat/catalog/13490.json
{
    "id": "CVE-2018-13490",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for FILM, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/FILM"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "FILM",
        "address": "0x66b11115e070269d65400ea359a72d643804cc2f"
    },
    "signature": "c5d1692d61e04ef626bbae2253006abb"
}

=== manifoldfinance/defi-threat/catalog/12062.json
{
    "id": "CVE-2018-12062",
    "title": "Improper Access Control",
    "description": "The sell function of a smart contract implementation for SwftCoin (SWFTC), a tradable Ethereum ERC20 token, allows a potential trap that could be used to cause financial damage to the seller, because of overflow of the multiplication of its argument amount and a manipulable variable sellPrice, aka the \"tradeTrap\" issue.\n",
    "references": ["https://peckshield.com/2018/06/11/tradeTrap/"],
    "credits": "peckshield.com",
    "vulnerability_type": {
        "cwe": "CWE-284",
        "swc": "SWC-105"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "SwftCoin",
        "address": "0x0bb217e40f8a5cb79adf04e1aab60e5abd0dfc1e"
    },
    "signature": "649feaad833f4ca3539d83beedcabc3f"
}

=== manifoldfinance/defi-threat/catalog/13687.json
{
    "id": "CVE-2018-13687",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for normikaivo, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/normikaivo"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "normikaivo",
        "address": "0xd71e21055f4b0ff413f5fa826b79c511a10bae6c"
    },
    "signature": "f818be4ab61fcfcd1e723225c5fae3f0"
}

=== manifoldfinance/defi-threat/catalog/13083.json
{
    "id": "CVE-2018-13083",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for Plaza Token (PLAZA), an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": ["https://github.com/VenusADLab/EtherTokens/blob/master/PlazaToken/PlazaToken.md"],
    "credits": "VenusADLab",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "PlazaToken",
        "address": "0x332124F226e80c3AFdBb59271f550881b20604A1"
    },
    "signature": "d5f59b0ecea7b8af52a987d560580608"
}

=== manifoldfinance/defi-threat/catalog/13723.json
{
    "id": "CVE-2018-13723",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for SERVVIZIOToken, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/SERVVIZIOToken"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "SERVVIZIOToken",
        "address": "0x338649003ff30194be899100b67a00bbcd62af67"
    },
    "signature": "c5d1692d61e04ef626bbae2253006abb"
}

=== manifoldfinance/defi-threat/catalog/13548.json
{
    "id": "CVE-2018-13548",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for Mimicoin, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/Mimicoin"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "Mimicoin",
        "address": "0x475a1bdf009386294d52364f889b25782a093f90"
    },
    "signature": "7f261c4b9c53c4e91d55c45fe51e03a7"
}
