=== manifoldfinance/defi-threat/src/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "description": "",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "minLength": 1
        },
        "title": {
            "type": "string",
            "minLength": 1
        },
        "description": {
            "type": "string",
            "minLength": 1
        },
        "references": {
            "type": "array",
            "items": {
                "required": [
                    "contract_address"
                ],
                "properties": {}
            }
        },
        "credits": {
            "type": "string",
            "minLength": 1
        },
        "vulnerability_type": {
            "type": "object",
            "properties": {
                "cwe": {
                    "type": "string",
                    "minLength": 1
                },
                "swc": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "cwe",
                "swc"
            ]
        },
        "severity": {
            "type": "number"
        },
        "affected": {
            "type": "object",
            "properties": {
                "contractName": {
                    "type": "string",
                    "minLength": 1
                },
                "address": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "contractName",
                "address"
            ]
        },
        "signature": {
            "type": "string",
            "minLength": 1
        }
    },
    "required": [
        "id",
        "title",
        "description",
        "references",
        "credits",
        "vulnerability_type",
        "severity",
        "affected",
        "signature"
    ]
}

=== manifoldfinance/defi-threat/catalog/11329.json
{
    "id": "CVE-2018-11329",
    "title": "Improper Access Control",
    "description": "The DrugDealer function of a smart contract implementation for Ether Cartel, an Ethereum game, allows attackers to take over the contract's ownership, aka ceoAnyone. After that, all the digital assets (including Ether balance and tokens) might be manipulated by the attackers, as exploited in the wild in May 2018.\n",
    "references": ["https://peckshield.com/2018/05/21/ceoAnyone/"],
    "credits": "peckshield.com",
    "vulnerability_type": {
        "cwe": "CWE-284",
        "swc": "SWC-105"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "EtherCartel",
        "address": "0x5088b94cf8a1143eb228b6d3f008350ca742ddc2"
    },
    "signature": "71950f32ed8a07c253354aa7be0f2eaf"
}

=== manifoldfinance/defi-threat/catalog/13131.json
{
    "id": "CVE-2018-13131",
    "title": "Integer Overflow or Wraparound",
    "description": "SpadePreSale is a smart contract running on Ethereum. The mint function has an integer overflow that allows minted tokens to be arbitrarily retrieved by the contract owner.\n",
    "references": [
        "https://github.com/dwfault/AirTokens/blob/master/SPXToken/mint%20interger%20overflow.md",
        "https://github.com/dwfault/AirTokens/tree/master/SpadePreSale"
    ],
    "credits": "dwfault",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "SpadePreSale",
        "address": "0x50ca2de80e803bf4b00f188545bca959540c5582"
    },
    "signature": "37a6cd24ed0a87333f847c750462552e"
}

=== manifoldfinance/defi-threat/catalog/13207.json
{
    "id": "CVE-2018-13207",
    "title": "Integer Overflow or Wraparound",
    "description": "The sell function of a smart contract implementation for PornCoin (PRNC), an Ethereum token, has an integer overflow in which \"amount * sellPrice\" can be zero, consequently reducing a seller's assets.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/ETHEREUMBLACK/sell%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/PornCoin"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "PornCoin",
        "address": "0xc310755f88145cabcaa06c714cd668b5465dceaa"
    },
    "signature": "649feaad833f4ca3539d83beedcabc3f"
}

=== manifoldfinance/defi-threat/catalog/13754.json
{
    "id": "CVE-2018-13754",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for CryptosisToken, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/CryptosisToken"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "CryptosisToken",
        "address": "0x61eb2155714b877e95bfb27be10724075c113fe6"
    },
    "signature": "d5f59b0ecea7b8af52a987d560580608"
}

=== manifoldfinance/defi-threat/catalog/13198.json
{
    "id": "CVE-2018-13198",
    "title": "Integer Overflow or Wraparound",
    "description": "The sell function of a smart contract implementation for STeX Exchange ICO (STE), an Ethereum token, has an integer overflow in which \"amount * sellPrice\" can be zero, consequently reducing a seller's assets.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/ETHEREUMBLACK/sell%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/STE"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "STE",
        "address": "0xeba49ddea9f59f0a80ecbb1fb7a585ce0bfe5a5e"
    },
    "signature": "2ea98a1b817cc68a824fdb27640c0464"
}

=== manifoldfinance/defi-threat/catalog/13510.json
{
    "id": "CVE-2018-13510",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for Welfare Token Fund (WTF), an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/WelfareTokenFund"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "WelfareTokenFund",
        "address": "0x83b6aD8E37Ab7A4F71da533A35271484270EC6c2"
    },
    "signature": "f2dea3f6ecb1397e9005efbd42dc90aa"
}

=== manifoldfinance/defi-threat/catalog/13182.json
{
    "id": "CVE-2018-13182",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for loncoin (LON), an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/loncoin"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "loncoin",
        "address": "0x25a9ebaa3d391448c2e9b9d5d7be0c7e52873489"
    },
    "signature": "f818be4ab61fcfcd1e723225c5fae3f0"
}

=== manifoldfinance/defi-threat/catalog/13657.json
{
    "id": "CVE-2018-13657",
    "title": "Integer Overflow or Wraparound",
    "description": "The mintToken function of a smart contract implementation for Rice, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.\n",
    "references": [
        "https://github.com/BlockChainsSecurity/EtherTokens/blob/master/GEMCHAIN/mint%20integer%20overflow.md",
        "https://github.com/BlockChainsSecurity/EtherTokens/tree/master/Rice"
    ],
    "credits": "BlockChainsSecurity",
    "vulnerability_type": {
        "cwe": "CWE-190",
        "swc": "SWC-101"
    },
    "severity": 7.5,
    "affected": {
        "contractName": "Rice",
        "address": "0xad5de4de1a10353126460ead7dfe52e836f4b64d"
    },
    "signature": "f2dea3f6ecb1397e9005efbd42dc90aa"
}
